### PR TITLE
Word list update

### PR DESCRIPTION
**Pull request by Guidanel**
- Word list updated using wwwjdic (kana and definition)
- File with more details added (inc. multiple definitions separated by <br>)

### CODE REVIEW

**Comment by CallumBeaney** [comment]
Thank you very much Guillaume!
Merged and made minor adjustments.

**Comment by Guidanel** [comment]
Cool! Glad I could be of help!
Is the game already using the updated version?

**Comment by CallumBeaney** [comment]
It is! I plan to incorporate the extended version in coming days as well as a couple of extra functionalities like CSV export etc etc

**Comment by Guidanel** [comment]
Excellent! I'll play it regularly from now on then! :)

Cheers!

**Comment by Guidanel** [comment]
Hi!

As I was playing I noticed that it is possible to repeatedly validate a
yellow word to increase the score. It's not a real issue but just wanted to
let you know.

Cheers,

Guillaume

**Comment by CallumBeaney** [comment]
Hi Guillaume, I'm sorry for my slow reply! I will fix this and also implement a "reveal one pair" button that will impact the user's score -- when playing the mandarin version last week I got onto an incredibly hard grid and realised it might be welcomed ;)

After this CSV export will probably be in order.

**Comment by Guidanel** [comment]
No worries, thanks for the update! I'll definitely use the "reveal one
pair" button! :D

**Pull request merged**
